@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMyYTM5MGUzLTAyZGUtNDcwOS1iZDZhLTYyNmIzYmI1MDNjNCIsImlhdCI6MTY2ODU0MzQ2MSwiZXhwIjoxNjY4NjI5ODYxfQ.DmPD1LemMjHYOVD1q0ljIxgndn4mOtgzVBuV5-RWjMc

###create user
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "matheus",
    "email": "matheus@gmail.com",
    "password": "123456"
}

###login
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "matheus@gmail.com",
    "password": "123456"
}

###insert new client
POST http://localhost:3003/client/insert
Authorization: {{token}}
Content-Type: application/json

{
    "name": "matheus moraes",
    "cpf": 12345678790,
    "birth": "05072000",
    "fathersname": "rubem soares",
    "mothersname": "andreia moraes",
    "cep": 45603090,
    "logradouro": "Rua Ariston Caldas",
    "complemento": "1 andar",
    "bairro": "Pontalzinho",
    "localidade": "Itabuna",
    "uf": "BA",
    "ibge": 2914802,
    "gia": 1,
    "ddd": 73,
    "siafi": 3597
}

###get all clients
GET http://localhost:3003/client/getAll
Authorization: {{token}}

###delete client by id
DELETE http://localhost:3003/client/delete
Authorization: {{token}}
Content-Type: application/json

{
    "id": "0af16f6b-8c49-4359-96c3-b1267151015f"
}

###edit client
PUT http://localhost:3003/client/edit
Authorization: {{token}}
Content-Type: application/json

{
    "id": "7d703b27-017b-416d-a50b-e424044cea5d",
    "name": "daniel daniel",
    "cpf": 99999999999
}