@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMyYTM5MGUzLTAyZGUtNDcwOS1iZDZhLTYyNmIzYmI1MDNjNCIsImlhdCI6MTY2ODY1NjcwNywiZXhwIjoxNjY4NzQzMTA3fQ.N0FPdTk-QmPiw9eLWngyhTnZIEAFmGbJKZxnfGeIFhM

###create user
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "matheus",
    "email": "augusto@gmail.com",
    "password": "123456"
}

###login
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "matheus@gmail.com",
    "password": "123456"
}

###insert new client
POST http://localhost:3003/client/insert
Authorization: {{token}}
Content-Type: application/json

{
    "name": "joaozinho",
    "cpf": 12345678232,
    "birth": "2000-07-05",
    "fathersname": "rubem soares",
    "mothersname": "andreia moraes",
    "cep": "45603090",
    "logradouro": "Rua Ariston Caldas",
    "complemento": "1 andar",
    "bairro": "Pontalzinho",
    "localidade": "Itabuna",
    "uf": "BA",
    "ibge": 2914802,
    "gia": "",
    "ddd": 73,
    "siafi": 3597
}

###get all clients
GET http://localhost:3003/client/getAll
Authorization: {{token}}

###get client by id
GET http://localhost:3003/client/efb340ad-0c7f-456c-b48a-de4a0dec441d
Authorization: {{token}}

###delete client by id
DELETE http://localhost:3003/client/delete
Authorization: {{token}}
Content-Type: application/json

{
    "id": "efb340ad-0c7f-456c-b48a-de4a0dec441d"
}

###edit client
PUT http://localhost:3003/client/edit
Authorization: {{token}}
Content-Type: application/json

{
    "id": "39f009b2-bdb2-44c6-8e82-644a0fa95442",
    "name": "daniel daniel",
    "cpf": 99999999999
}